### ISSUE TITLE
Human Library

### ISSUE THREAD

**Issue by lghasemzadeh** [okeoke85/ADEBAProjectWinForm#1]
Hello @okeoke85

This is Leila Ghasemzadeh, studying Computer Science at Istanbul Technical University.
I have been struggling using the Human library, and through the issues I saw your comments. I have several questions and since I guess you are Iranian I feel more comfortable to ask you my questions.

Waiting for your response.
Thank you

**Comment by okeoke85** [comment]
Hi lghasemzadeh,

I'm not Iranian, and you can ask the owner of the project i guess, i'm new at human too.
